### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by noony** [funi-main/ectoken#1]
Is it possible to have a branch with php7 support ?

RETVAL_STRINGL only have 2 args now.
zend_parse_parameters string ('s') return size_t instead of int

**Comment by cgill27** [comment]
Were you able to resolve this?
I ran into the same issue and was curious if there's a workaround.
Ubuntu 16.04  PHP 7.0.4

**Comment by austinhquinn** [comment]
on like 139 of ectoken.c remove the third parameter ', 1' from the call to RETVAL_STRINGL

then make, make test, make install =D

Er the above was for the old version, i forked and fixed the three lines
https://github.com/austinhquinn/ectoken

**Comment by noony** [comment]
👍
